name: Package exe with PyInstaller - Windows

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: PyInstaller Windows
      uses: JackMcKew/pyinstaller-action-windows@main
      with:
        path: .
        spec: AWSGlueManager.windows.spec

    - uses: actions/upload-artifact@v2
      with:
        name: AWSGlueManager
        path: dist/windows/AWSGlueManager_windows.zip
